package rev.streams.model;

import java.time.LocalDate;
import java.util.List;

public class EmployeeDataFactory {

  public static List<Employee> createSampleEmployees() {
    return List.of(
        new Employee(
            1L,
            "Alice",
            "Johnson",
            "Female",
            "alice.johnson@company.com",
            "Engineering",
            Position.DIRECTOR,
            145000.0,
            LocalDate.of(2018, 3, 15),
            LocalDate.of(1985, 7, 20),
            null,
            EmploymentStatus.ACTIVE,
            List.of("Java", "Architecture", "Leadership", "Microservices"),
            new Address("123 Tech St", "San Francisco", "CA", "94105", "USA")),
        new Employee(
            2L,
            "Bob",
            "Smith",
            "Male",
            "bob.smith@company.com",
            "Engineering",
            Position.SENIOR,
            95000.0,
            LocalDate.of(2020, 6, 1),
            LocalDate.of(1992, 3, 15),
            1L,
            EmploymentStatus.ACTIVE,
            List.of("Java", "Spring Boot", "AWS", "Docker"),
            new Address("456 Code Ave", "San Francisco", "CA", "94103", "USA")),
        new Employee(
            3L,
            "Charlie",
            "Brown",
            "Male",
            "charlie.brown@company.com",
            "Engineering",
            Position.LEAD,
            110000.0,
            LocalDate.of(2019, 1, 10),
            LocalDate.of(1988, 11, 8),
            1L,
            EmploymentStatus.ACTIVE,
            List.of("JavaScript", "React", "Node.js", "TypeScript"),
            new Address("789 Web Blvd", "San Jose", "CA", "95110", "USA")),
        new Employee(
            4L,
            "Diana",
            "Prince",
            "Female",
            "diana.prince@company.com",
            "HR",
            Position.MANAGER,
            105000.0,
            LocalDate.of(2017, 8, 20),
            LocalDate.of(1983, 5, 12),
            null,
            EmploymentStatus.ACTIVE,
            List.of("Recruitment", "Training", "Compliance", "Leadership"),
            new Address("321 People St", "Oakland", "CA", "94612", "USA")),
        new Employee(
            5L,
            "Eve",
            "Williams",
            "Female",
            "eve.williams@company.com",
            "HR",
            Position.SENIOR,
            82000.0,
            LocalDate.of(2021, 4, 12),
            LocalDate.of(1995, 9, 3),
            4L,
            EmploymentStatus.ACTIVE,
            List.of("Onboarding", "Employee Relations", "Communication"),
            new Address("654 Care Dr", "Berkeley", "CA", "94704", "USA")),
        new Employee(
            6L,
            "Frank",
            "Miller",
            "Male",
            "frank.miller@company.com",
            "Sales",
            Position.DIRECTOR,
            135000.0,
            LocalDate.of(2015, 2, 5),
            LocalDate.of(1978, 12, 25),
            null,
            EmploymentStatus.ACTIVE,
            List.of("B2B Sales", "Negotiation", "CRM", "Strategy"),
            new Address("987 Deal St", "San Francisco", "CA", "94102", "USA")),
        new Employee(
            7L,
            "Grace",
            "Lee",
            "Female",
            "grace.lee@company.com",
            "Sales",
            Position.SENIOR,
            88000.0,
            LocalDate.of(2020, 9, 18),
            LocalDate.of(1991, 4, 7),
            6L,
            EmploymentStatus.ACTIVE,
            List.of("Lead Generation", "Client Relations", "Presentations"),
            new Address("147 Growth Ave", "Palo Alto", "CA", "94301", "USA")),
        new Employee(
            8L,
            "Henry",
            "Davis",
            "Male",
            "henry.davis@company.com",
            "Sales",
            Position.LEAD,
            98000.0,
            LocalDate.of(2019, 7, 22),
            LocalDate.of(1987, 8, 14),
            6L,
            EmploymentStatus.ACTIVE,
            List.of("Account Management", "Sales Strategy", "Analytics"),
            new Address("258 Revenue Rd", "San Mateo", "CA", "94401", "USA")),
        new Employee(
            9L,
            "Ivy",
            "Chen",
            "Female",
            "ivy.chen@company.com",
            "Engineering",
            Position.MANAGER,
            125000.0,
            LocalDate.of(2016, 11, 30),
            LocalDate.of(1982, 6, 18),
            1L,
            EmploymentStatus.ACTIVE,
            List.of("System Design", "Scalability", "Team Leadership", "Cloud"),
            new Address("369 Scale St", "Mountain View", "CA", "94040", "USA")),
        new Employee(
            10L,
            "Jack",
            "Wilson",
            "Male",
            "jack.wilson@company.com",
            "Finance",
            Position.MANAGER,
            115000.0,
            LocalDate.of(2019, 5, 8),
            LocalDate.of(1985, 1, 30),
            null,
            EmploymentStatus.ACTIVE,
            List.of("Financial Analysis", "Budgeting", "Reporting", "Excel"),
            new Address("741 Money Ln", "San Francisco", "CA", "94104", "USA")),
        new Employee(
            11L,
            "Kate",
            "Martinez",
            "Female",
            "kate.martinez@company.com",
            "Finance",
            Position.SENIOR,
            89000.0,
            LocalDate.of(2021, 1, 14),
            LocalDate.of(1993, 10, 22),
            10L,
            EmploymentStatus.ACTIVE,
            List.of("Accounting", "Tax", "Compliance", "Audit"),
            new Address("852 Ledger Dr", "San Jose", "CA", "95112", "USA")),
        new Employee(
            12L,
            "Leo",
            "Anderson",
            "Male",
            "leo.anderson@company.com",
            "Engineering",
            Position.SENIOR,
            96000.0,
            LocalDate.of(2020, 3, 25),
            LocalDate.of(1990, 2, 14),
            9L,
            EmploymentStatus.ACTIVE,
            List.of("DevOps", "Docker", "Kubernetes", "CI/CD"),
            new Address("963 Pipeline Ave", "Fremont", "CA", "94538", "USA")),
        new Employee(
            13L,
            "Maria",
            "Garcia",
            "Female",
            "maria.garcia@company.com",
            "Marketing",
            Position.LEAD,
            92000.0,
            LocalDate.of(2021, 8, 5),
            LocalDate.of(1994, 7, 9),
            null,
            EmploymentStatus.ACTIVE,
            List.of("Digital Marketing", "SEO", "Content", "Analytics"),
            new Address("159 Brand St", "San Francisco", "CA", "94107", "USA")),
        new Employee(
            14L,
            "Nathan",
            "Taylor",
            "Male",
            "nathan.taylor@company.com",
            "Marketing",
            Position.JUNIOR,
            68000.0,
            LocalDate.of(2022, 2, 10),
            LocalDate.of(1998, 11, 5),
            13L,
            EmploymentStatus.PROBATION,
            List.of("Social Media", "Analytics", "Copywriting"),
            new Address("357 Social Rd", "Oakland", "CA", "94611", "USA")),
        new Employee(
            15L,
            "Olivia",
            "Moore",
            "Female",
            "olivia.moore@company.com",
            "Engineering",
            Position.LEAD,
            108000.0,
            LocalDate.of(2018, 10, 12),
            LocalDate.of(1986, 4, 28),
            9L,
            EmploymentStatus.ACTIVE,
            List.of("Machine Learning", "Python", "TensorFlow", "Data Science"),
            new Address("486 AI Blvd", "Palo Alto", "CA", "94306", "USA")),
        new Employee(
            16L,
            "Paul",
            "White",
            "Male",
            "paul.white@company.com",
            "Engineering",
            Position.JUNIOR,
            75000.0,
            LocalDate.of(2022, 6, 20),
            LocalDate.of(1999, 3, 17),
            9L,
            EmploymentStatus.PROBATION,
            List.of("Java", "Git", "Testing"),
            new Address("597 Code St", "San Jose", "CA", "95126", "USA")),
        new Employee(
            17L,
            "Quinn",
            "Roberts",
            "Female",
            "quinn.roberts@company.com",
            "Finance",
            Position.JUNIOR,
            72000.0,
            LocalDate.of(2022, 9, 1),
            LocalDate.of(1998, 8, 23),
            10L,
            EmploymentStatus.ACTIVE,
            List.of("Financial Modeling", "Excel", "PowerBI"),
            new Address("608 Finance Dr", "San Francisco", "CA", "94108", "USA")),
        new Employee(
            18L,
            "Rachel",
            "Thomas",
            "Female",
            "rachel.thomas@company.com",
            "Sales",
            Position.JUNIOR,
            70000.0,
            LocalDate.of(2023, 1, 15),
            LocalDate.of(2000, 1, 12),
            6L,
            EmploymentStatus.PROBATION,
            List.of("Cold Calling", "CRM", "Communication"),
            new Address("719 Sales Ave", "San Mateo", "CA", "94403", "USA")),
        new Employee(
            19L,
            "Steve",
            "Jackson",
            "Male",
            "steve.jackson@company.com",
            "HR",
            Position.JUNIOR,
            69000.0,
            LocalDate.of(2023, 3, 1),
            LocalDate.of(1997, 12, 8),
            4L,
            EmploymentStatus.ACTIVE,
            List.of("Recruitment", "Interviewing", "Communication"),
            new Address("820 Hire St", "Oakland", "CA", "94618", "USA")),
        new Employee(
            20L,
            "Tina",
            "Harris",
            "Female",
            "tina.harris@company.com",
            "Marketing",
            Position.SENIOR,
            85000.0,
            LocalDate.of(2020, 11, 10),
            LocalDate.of(1989, 5, 16),
            13L,
            EmploymentStatus.ACTIVE,
            List.of("Brand Strategy", "Campaign Management", "Analytics"),
            new Address("931 Brand Ln", "Berkeley", "CA", "94709", "USA")));
  }

  public static List<Department> createSampleDepartments() {
    return List.of(
        new Department(1L, "Engineering", "ENG", 1L, 5000000.0, "San Francisco HQ"),
        new Department(2L, "HR", "HR", 4L, 800000.0, "Oakland Office"),
        new Department(3L, "Sales", "SALES", 6L, 1200000.0, "San Francisco HQ"),
        new Department(4L, "Finance", "FIN", 10L, 600000.0, "San Francisco HQ"),
        new Department(5L, "Marketing", "MKT", 13L, 900000.0, "San Francisco HQ"));
  }

  public static List<Project> createSampleProjects() {
    return List.of(
        new Project(
            1L,
            "Cloud Migration",
            "CLOUD-001",
            1L,
            LocalDate.of(2024, 1, 1),
            LocalDate.of(2024, 12, 31),
            ProjectStatus.IN_PROGRESS,
            2000000.0),
        new Project(
            2L,
            "Mobile App Development",
            "MOB-001",
            1L,
            LocalDate.of(2024, 3, 1),
            LocalDate.of(2024, 9, 30),
            ProjectStatus.IN_PROGRESS,
            1500000.0),
        new Project(
            3L,
            "Employee Self-Service Portal",
            "HR-001",
            2L,
            LocalDate.of(2024, 2, 1),
            LocalDate.of(2024, 8, 31),
            ProjectStatus.IN_PROGRESS,
            500000.0),
        new Project(
            4L,
            "New CRM Implementation",
            "SALES-001",
            3L,
            LocalDate.of(2024, 1, 15),
            LocalDate.of(2024, 7, 15),
            ProjectStatus.COMPLETED,
            800000.0),
        new Project(
            5L,
            "Financial Reporting System",
            "FIN-001",
            4L,
            LocalDate.of(2024, 4, 1),
            LocalDate.of(2024, 10, 31),
            ProjectStatus.IN_PROGRESS,
            600000.0));
  }
}
